### PR TITLE
Adjusting to add an option to avoid certificate checking when connecting using TLS

### PR DESCRIPTION
**Pull request by Ellerbach**
Adjusting to add an option to avoid certificate checking when connecting using TLS
- Surface the option in the MQTT Client class thru the MqttSettings
- Surface the option in the Mqtt transport class
- Adjusting the Mok class used in test
- Adjusting documentation

### CODE REVIEW

**Comment by alberk8** [comment]
I have tested without the certificatecheck (test.mosquitto.org) and it seems to work so far.  I have it running a 10 seconds publish loop for 3 hours.

image

**Comment by Ellerbach** [comment]
> I have tested without the certificatecheck (test.mosquitto.org) and it seems to work so far. I have it running a 10 seconds publish loop for 3 hours.

Thanks a lot! So it is working nicely then.

**Review by josesimoes — COMMENTED** [review]
Considering that the default is `true` and that we should emphasize that the secured way it's the default and preferred one, I would call this property instead `DisableCertificateCheck` and reverse the property assignment (which is `false` for bool) and the code using it.

And add a remark on the comment to stress it. Something like: "Setting this property will bypass the validation of the server root CA certificate. Using the library this way it's unsecured and, therefore, not recommended."

**Comment by Ellerbach** [comment]
> Considering that the default is `true` and that we should emphasize that the secured way it's the default and preferred one, I would call this property instead `DisableCertificateCheck` and reverse the property assignment (which is `false` for bool) and the code using it.

As a patter, properties should represent something positive. Otherwise it's miss leading. It's like for feature flags and anything related. The default value can be anything. If we are using `DisableCertificateCheck`, I'll be tempted to set if to false to disable while the expected behaviour on what you describe is the opposite. The other way around has no ambiguity. It's the reason why always positive elements are used.

**Comment by josesimoes** [comment]
I beg to differ... 😁 

I'm all for the positive naming of properties. And, even more important, not forcing double negations and negate the positive and all that, but in this specific situation, the name it's highlighting/stressing what's about to happen: that the certificate check is to be DISABLED. On purpose. And opposed to what normally would happen if one doesn't touch anything.
And of course, one can set the property default value to make it the safe one, but that's not the point. It's the behavior. 

You can find this pattern on controls, for example, on which is common to use Disable to... _disable_ something that's usually enabled (as default). Because one wants to convey exactly that message: "hey! this is usually ON but you can choose to have it OFF".
I don't think I wouldn't be tempted to turn off a border on a control by setting it's _disable_ property to false. Unless I'm distracted. But that would be caught in a code review. 😉 

Moreover, usage of _disable_ in property names (and methods) is not forbidden in .NET naming guidelines and it's used extensively throughout the .NET API:
https://docs.microsoft.com/en-us/search/?terms=disable&category=Reference&products=%2Fdevrel%2F7696cda6-0510-47f6-8302-71bb5d2e28cf

**Comment by Ellerbach** [comment]
> Moreover, usage of _disable_ in property names (and methods) is not forbidden in .NET naming guidelines and it's used extensively throughout the .NET API:

The "Disable" property is an alone one ;-) Not with additional elements. And it should be "Enabled" ;-) We have this pattern using "Enabled" and only positive naming in .NET IoT. We may have some that went thru but all up, it should be positive.

Now if you have really a super strong opinion, happy to adjust.

**Comment by josesimoes** [comment]
> Now if you have really a super strong opinion, happy to adjust.

Not super strong, more _mildly_ strong... Just want to be sure that we convey the right message with this.

But OK, let's go with the positive name then. If that's the case than we should go with the usual pattern: verb + noun (it's backwards now). 

And, as we are looking at it, let's be absolutely clear with this and state that this is about the server certificate. 
Something like: `ValidateServerCertificate`? Or `PerformServerCertificateValidation` (maybe tooo verbose)?

**Comment by Ellerbach** [comment]
I will rename to this: `ValidateServerCertificate` which, you are right is much more clear and positive ;-)

**Comment by Ellerbach** [comment]
@josesimoes so seems like all green and now all good with new naming, ok to merge?

**Review by josesimoes — APPROVED** [review]
LGTM!

**Pull request merged**
