### PR TITLE
Fix memory issue and improve performance

### PR DESCRIPTION
**Pull request by Ellerbach**
## Description

Fixing memory issue when intense usage and improving all up performances

## Motivation and Context

- Fixes nanoFramework/Home#816
- Improve performances

## How Has This Been Tested?

On a real device with sample sending message ID and memory available which has been used to raise the issue.

## Screenshots

image

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
WOW!! Awesome improvements! 💯

**Comment by josesimoes** [comment]
@Ellerbach care to check sonarcloud analysis and maybe address the code smell and/or the potential duplicated code?

**Comment by Ellerbach** [comment]
> @Ellerbach care to check sonarcloud analysis and maybe address the code smell and/or the potential duplicated code?

Done, it's about code replication. But would require a full rework on the engine to avoid it. I marked as "won't fix".

**Comment by josesimoes** [comment]
Ignoring sonarcloud failure.

**Pull request merged**
