### PR TITLE
Support custom mqtt channel

### PR DESCRIPTION
**Pull request by sake402**
Sometimes user dont neccessarily want to use the System.Net as the Mqtt Connection channel. 

## Description
Provide a setter method of IMqttNetworkChannel on MqttClient

## Motivation and Context
For example, I needed to use a SIM800 as an alternative internet connection route for Mqtt mesages by simply providing my custom implementation of IMqttNetworkChannel

## How Has This Been Tested?
Using our own implementation of IMqttNetworkChannel 

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Comment by Ellerbach** [comment]
@sake402 is this PR still valid? If yes, please rebase, there has been quite some changes.

**Comment by josesimoes** [comment]
@Ellerbach could you please review this one and merge or dismiss or...

**Comment by Ellerbach** [comment]
I will close this PR as open for more than a year and no answer from the main contributor. We can always reopen if needed

**Pull request closed without merging**
